'use strict';
const $=id=>document.getElementById(id), escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,template='',catalog=[],state={pool:[],drafts:[],active:null},saveQueue=Promise.resolve();
const active=()=>state.drafts.find(d=>d.id===state.active);
function status(message){$('status').textContent=message}
function draft(){return {id:crypto.randomUUID(),name:'Untitled report',selected:[],updated:new Date().toISOString()}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('enemy-scout-manager',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspace');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function readState(){return new Promise((resolve,reject)=>{const r=db.transaction('workspace').objectStore('workspace').get('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function persist(){const snapshot=structuredClone(state);saveQueue=saveQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put(snapshot,'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}));saveQueue.catch(()=>status('Browser storage failed. Download a JSON backup now; changes remain in memory.'));return saveQueue}
function validateFight(f){if(!f||typeof f.id!=='string'||typeof f.start!=='string'||!Number.isFinite(f.seconds)||f.seconds<=0||!Array.isArray(f.actors)||!Array.isArray(f.squadActors))throw Error('Invalid fight summary');for(const a of [...f.actors,...f.squadActors]){if(typeof a.name!=='string'||typeof a.spec!=='string'||!Number.isFinite(a.damage))throw Error('Invalid actor summary')}return f}
function dataFromHTML(html){const doc=new DOMParser().parseFromString(html,'text/html');const node=doc.querySelector('script#report-data[type="application/json"]');if(!node)throw Error('This HTML is not an Enemy Scout report');return JSON.parse(node.textContent)}
function first(a,k,fallback={}){return a[k]?.[0]??fallback}
function convertEI(log,filename){
 if(log.mapID!==968||!log.detailedWvW||!log.durationMS)throw Error('Import requires detailed Edge of the Mists EI JSON (map 968).');
 const seconds=log.durationMS/1000,targets=log.targets||[],players=(log.players||[]).filter(p=>!p.notInSquad&&!p.friendlyNPC&&!p.isFake);
 function actor(a,isEnemy,index){const d=first(a,'dpsAll'),v=first(a,'defenses'),o=first(a,'statsAll'),skills={};for(const r of [...first(a,'totalDamageDist',[]),...(a.minions||[]).flatMap(m=>first(m,'totalDamageDist',[]))]){const prefix=r.indirectDamage?'b':'s',id=prefix+r.id,s=skills[id]??={id,name:log[prefix==='b'?'buffMap':'skillMap']?.[id]?.name||id,damage:0,hits:0,max:0,condition:prefix==='b'};s.damage+=r.totalDamage||0;s.hits+=r.connectedHits||0;s.max=Math.max(s.max,r.max||0)}const cum=first(a,'damage1S',[]);return {name:a.name||'Unknown',instanceID:a.instanceID,spec:a.profession||(a.name||'Unknown').replace(/ pl-\d+$/,''),team:String(a.teamID||0),damage:d.damage||0,power:d.powerDamage||0,condition:d.condiDamage||0,taken:v.damageTaken||0,downs:v.downCount||0,deaths:v.deadCount||0,cc:o.appliedCrowdControl||0,ccSeconds:(o.appliedCrowdControlDuration||0)/1000,stripsReceived:v.boonStrips||0,strips:first(a,'support').boonStrips??null,squadDamage:isEnemy?players.reduce((n,p)=>n+(p.dpsTargets?.[index]?.[0]?.damage||0),0):0,skills:Object.values(skills),timeline:cum.slice(1).map((n,i)=>Math.max(0,n-cum[i])),downTimes:(a.combatReplayData?.down||[]).map(r=>r[0]/1000),build:{reportedWeapons:[...new Set((a.weapons||[]).filter(w=>!['Unknown','2Hand','None',''].includes(w)))],weapons:[],procs:[],ccCandidates:[],stripCandidates:[],consumables:[]}}}
 const actors=targets.flatMap((a,i)=>a.enemyPlayer&&!a.isFake?[actor(a,true,i)]:[]),squadActors=players.map(a=>actor(a,false));const squad={};for(const k of ['damageTaken','powerDamageTaken','conditionDamageTaken','downCount','deadCount','receivedCrowdControl','boonStrips'])squad[k]=players.reduce((n,p)=>n+(first(p,'defenses')[k]||0),0);
 return {id:filename.replace(/\.json$/i,''),source:filename,start:log.timeStartStd||log.timeStart,seconds,squadCount:players.length,squad,squadActors,enemyCount:actors.length,actors,events:{available:false,reason:'Imported EI JSON without raw event attribution',cc:[],removals:[],conditions:[]},warnings:['EI JSON import: raw CC/boon-removal/condition attribution and inferred build metadata unavailable. Import a locally prepared bundle for full analysis.'],parserVersion:log.eliteInsightsVersion||'unknown'};
}
function importData(data,filename){let fights;if(data.eliteInsightsVersion&&data.players)fights=[convertEI(data,filename)];else{if(data.mapID!==968&&data.map!=='Edge of the Mists')throw Error('Only Edge of the Mists reports are supported');fights=data.fights}if(!Array.isArray(fights)||!fights.length)throw Error('No fights found');fights.forEach(validateFight);let added=0,duplicates=0;for(const f of fights){const original=f.originalID||f.id,existing=state.pool.find(p=>(p.originalID||p.id)===original&&p.start===f.start);if(existing){duplicates++;continue}const clean=structuredClone(f);clean.id=original+'--'+crypto.randomUUID().slice(0,8);clean.originalID=original;clean.source=(f.source||filename).split(/[\\/]/).pop();state.pool.push(clean);added++}return {added,duplicates}}
function visible(){const q=$('search').value.toLowerCase();return [...state.pool].sort((a,b)=>a.start.localeCompare(b.start)).filter(f=>(f.start+' '+f.source).toLowerCase().includes(q)&&(!$('selectedOnly').checked||active().selected.includes(f.id)))}
function render(){const a=active();$('reportName').value=a?.name||'';$('drafts').innerHTML=state.drafts.map(d=>`<button class="draft ${d.id===state.active?'active':''}" data-draft="${d.id}">${escapeHTML(d.name)}<br><small>${d.selected.length} fights</small></button>`).join('');for(const b of $('drafts').querySelectorAll('[data-draft]'))b.onclick=()=>{state.active=b.dataset.draft;render();persist()};const rows=visible();$('empty').hidden=!!rows.length;$('fights').innerHTML=rows.map(f=>`<tr><td><input type="checkbox" data-fight="${escapeHTML(f.id)}" aria-label="Include ${escapeHTML(f.start)}" ${a.selected.includes(f.id)?'checked':''}></td><td>${escapeHTML(f.start)}<br><small>${escapeHTML(f.source)}</small></td><td>${f.seconds.toFixed(1)}s</td><td>${f.squadCount}</td><td>${f.actors.length}</td></tr>`).join('');for(const c of $('fights').querySelectorAll('[data-fight]'))c.onchange=()=>{const selected=new Set(active().selected);c.checked?selected.add(c.dataset.fight):selected.delete(c.dataset.fight);active().selected=[...selected];render();persist()};$('summary').textContent=`${a.selected.length} selected fights · ${state.pool.length} available logs. Saved in this browser.`;for(const id of ['preview','download'])$(id).disabled=!a.selected.length||!template}
function reportData(){const a=active(),fights=state.pool.filter(f=>a.selected.includes(f.id)).sort((a,b)=>a.start.localeCompare(b.start));if(!fights.length)throw Error('Select at least one fight');const dates=[...new Set(fights.map(f=>f.start.slice(0,10)))];return {title:a.name,date:dates.length===1?dates[0]:dates[0]+' to '+dates.at(-1),map:'Edge of the Mists',mapID:968,selection:{date:dates[0],mapID:968,dateBasis:'Explicit report selection',logs:fights.map(f=>({file:f.source,selected:true,mapIDs:[968]}))},fights,rejected:[],missing:[]}}
function reportHTML(){const data=reportData();const payload=JSON.stringify(data).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');return template.replace(/(<script id="report-data" type="application\/json">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+payload+b).replace(/<title>.*?<\/title>/,()=>'<title>'+escapeHTML(data.title)+'</title>').replace('<h1>ENEMY SCOUT</h1>',()=>'<h1>'+escapeHTML(data.title)+'</h1>')}
function download(content,type,filename){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function filename(){return (active().name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'enemy-scout-report')+'-'+active().id.slice(0,8)}
async function published(){const item=catalog.find(r=>r.file===$('library').value);if(!item)throw Error('Choose a published report');const response=await fetch(item.file);if(!response.ok)throw Error('Unable to load report');const html=await response.text();const result=importData(dataFromHTML(html),item.file);if(!template)template=html;render();await persist();status(`Loaded ${result.added} fights; skipped ${result.duplicates} duplicates. Check the fights you want to include.`)}
async function init(){try{db=await openDB();state=(await readState())||state;if(!state.drafts.length){const d=draft();state.drafts.push(d);state.active=d.id}if(!active())state.active=state.drafts[0].id;const response=await fetch('library.json');if(!response.ok)throw Error('Library unavailable');catalog=await response.json();$('library').innerHTML=catalog.map(r=>`<option value="${escapeHTML(r.file)}">${escapeHTML(r.title)}</option>`).join('');if(catalog.length){const response=await fetch('report-template.html');if(!response.ok)throw Error('Report template unavailable');template=await response.text()}render();status('Ready. Create a draft and load or import the fights you want.')}catch(e){status(e.message+' — browser storage and site access are required.');}}
$('newReport').onclick=()=>{const d=draft();state.drafts.push(d);state.active=d.id;render();persist();$('reportName').focus()};$('reportName').oninput=()=>{active().name=$('reportName').value.trim()||'Untitled report';active().updated=new Date().toISOString();persist()};$('reportName').onchange=render;
$('deleteDraft').onclick=()=>{if(!confirm('Delete this browser draft? The logs and public report will remain unchanged.'))return;state.drafts=state.drafts.filter(d=>d.id!==state.active);if(!state.drafts.length)state.drafts.push(draft());state.active=state.drafts[0].id;render();persist()};
$('search').oninput=render;$('selectedOnly').onchange=render;
for(const [id,add]of [['addVisible',true],['removeVisible',false]])$(id).onclick=()=>{const selected=new Set(active().selected);for(const f of visible())add?selected.add(f.id):selected.delete(f.id);active().selected=[...selected];render();persist()};
$('save').onclick=async()=>{try{await persist();status('Draft saved in this browser.')}catch(e){status('Could not save: '+e.message)}};
$('loadPublished').onclick=()=>published().catch(e=>status(e.message));
$('importFiles').onchange=async e=>{const messages=[];for(const f of e.target.files){try{if(/\.(zevtc|evtc|zip)$/i.test(f.name))throw Error('Raw logs require local parsing. Use prepare_import.ps1, then import the output JSON.');const text=await f.text(),data=/\.html$/i.test(f.name)?dataFromHTML(text):JSON.parse(text),r=importData(data,f.name);messages.push(`${f.name}: ${r.added} added, ${r.duplicates} duplicates skipped.`)}catch(err){messages.push(f.name+': '+err.message)}}render();await persist();status(messages.join('\n'));e.target.value=''};
$('backup').onclick=()=>{try{download(JSON.stringify(reportData(),null,2),'application/json',filename()+'.json')}catch(e){status(e.message)}};
$('download').onclick=()=>{try{download(reportHTML(),'text/html',filename()+'.html');status('Report downloaded. Publish it with the local publishing script to get a public link.')}catch(e){status(e.message)}};
$('preview').onclick=()=>{try{const u=URL.createObjectURL(new Blob([reportHTML()],{type:'text/html'}));window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(e){status(e.message)}};
init();
